### ISSUE TITLE
Incorrect purge move speed

### ISSUE THREAD

**Issue by 310weber** [kyleisah/Klipper-Adaptive-Meshing-Purging#36]
In Line_Purge.cfg -Line 51 
```  {% set purge_move_speed = (cross_section * flow_rate) * 60 | float %}```

This yeilds a number with units mm^5/sec (mm^2 * mm^3/sec)

I believe it should be changed to the following:
```  {% set purge_move_speed = (flow rate / cross_section) * 60 | float %}```

**Comment by kyleisah** [comment]
That's what I get for working on new purges late at night I suppose. 😅 I'm actually working on revamping all of the macros a bit to improve the experience of people using Moonraker's Update Manager. This will also improve the experience of those who go the more traditional route though as well. 

I've made some helper macros that will just do the calculations and then push them all purge macros, and whatever purge macro is called will be able to verbose some good information. This also led me down the path of needing to rework how flow_rate is calculated.

I knew something was funky about the way it was calculated in `LINE_PURGE` but it still worked on my machines just fine.

If you'd please check my work here, this is how purge_move_speed (flow) will be calculated in an upcoming release. Remember, these are not finalized, but is just a way to get what was in my mind into vscode:

The variables for purging here:
```yaml
# The following variables are for adjusting PURGE settings for KAMP.
variable_adaptive_purging_enable: False     # Set to True to enable adaptive purging with KAMP.
variable_tip_distance: 0                    # Distance between tip of filament and nozzle before purge. Useful for reliable and consistent purging.
variable_y_distance_to_object:  5           # Distance between purge line and print area.
variable_flow_rate: 12                      # Desired flow rate for purge. Standard flow hotends are ~12, high flow are ~24.
variable_purge_amount: 25                   # Amount in millimeters of filament to purge.
```

The helper macro here:
```yaml
[gcode_macro _KAMP_Purge_Calculate]
description: HELPER - Gets any params KAMP requires for purging and calculates purge variables
gcode:

    # Get nozzle diameter from printer.cfg.
    {% set nozzle_dia = printer.configfile.config.extruder.nozzle_diameter | float %}

    # Set purge Z height to be 75% of nozzle diameter.
    {% set z_height = nozzle_dia * 0.75 %}
    {% set purge_speed = (flow_rate / nozzle_dia / z_height) * 60 | float %}
```

**Comment by kyleisah** [comment]
Hmm, now that I'm looking at this again, I think my math is wrong.

**Comment by kyleisah** [comment]
No, no, I believe that's correct.

If `flow_rate` is `12` and the line_width(`nozzle_dia`) is 0.4, and the `z_height` is 0.3, that would mean the fastest you could purge is at a speed of 100mm/s. 100mm/s * 60, 6000mm/m would be the feedrate.

**Comment by 310weber** [comment]
That looks correct to me but it makes the assumption that the purge line is only as wide as the nozzle diameter.  

As I looked through the current line purge macro more I came to the conclusion it is over constrained.  The user can specify purge amount, nozzle height, and line length, and the line width is assumed to be equal to nozzle diameter. The reality is that if you increase purge amount without increasing line length or nozzle height, the line will ultimately just squish out wider. The problem is that the speed calculation uses the assumed line width (cross section) so you'll end up inadvertently increasing flow rate because the speed calculation doesn't know how wide the line will actually be. 

I was thinking along the same lines as your helper macros for common extrude calculations. My plan was to have two:
- One would allow you to specify purge amount (along with flow rate, nozzle height, and line width), and it would output line length and speed. It would throw an error if line length exceeds some maximum, e.g. the bed length - start position. 
- The second would allow you to specify purge line length (along with flow rate, nozzle height and line width), and it would output the purge amount and speed. It would throw an error if purge amount exceeds the klipper max of 50 mm.

**Comment by kyleisah** [comment]
One thing I'm considering is just defining amount to purge, and flow rate, and the macro will take the x_min and x_max of the print area, move up y_distance_to_object, and then work out a decent purge line from those constraints. It's really hard to get this to work for any possible combination *and* keep defined variables to a minimum. 

Maybe something like `flowrate / purge_amount * calculated_length_from_print_area`?

**Comment by 310weber** [comment]
That sounds like a good aproach for this application.  People are likely to be more interested in specifying the amount of filament to be purged rather than the length of the line.  Just take the flow rate and amount as input and let the macro calculate reasonable values for the rest.

I'll link to whatever I come up with in the next couple days and am happy to review your solution when it's ready as well.

**Comment by kyleisah** [comment]
I'd love another pair of eyes on this if you want to give it a shot!

Any purge macro/method you come up with, these are the variables that are being standardized for all purges:

```yaml
variable_tip_distance: 0
variable_y_distance_to_object: 0
variable_flow_rate: 0
variable_purge_amount: 0
```
Looking forward to seeing what you come up with!
